---
title: "__TITLE__"
author: "daniel.lundin@lnu.se"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
    bookdown::html_document2:
        toc: yes
        toc_float:
          collapse: no
        fig_caption: yes
        code_folding: hide
    pdf_document:
        fig_caption: yes
        fig_height: 9
        fig_width: 8
        number_sections: yes
        toc: yes
bibliography:
    - grateful-refs.bib
---

```{r setup, echo=F, cache = FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path='figures/', cache = TRUE, fig.width = 10)
ggplot2::theme_set(ggplot2::theme_bw())
```

```{r libraries, message = FALSE, cache = FALSE, include = FALSE}
library(readr)
library(feather)
library(data.table)
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)
library(tidyr)
library(purrr)
library(stringr)
library(ggplot2)
library(kfigr)
library(knitr)
library(DT)
library(grateful)
```

```{r constants}
```

```{r read-data}
```

# Version history

# Summary

# Introduction

# Materials and Methods

## R and packages

This analysis was run with `r R.version$version.string`. Versions of packages used can be found in Table \@ref(tab:cite-packages).

```{r cite-packages, cache = FALSE}
cite_packages(output = "table", pkgs = "Session", out.dir = getwd()) %>%
  kable(
    caption = '**Versions of R and packages used in this analysis.**'
  )
```

# Results

# Discussion

# References
